/**
 * Bake a local 5etools checkout into the flat catalogue the screen reads.
 *
 *   npm run data:5etools -- --src "C:/path/to/5etools-src"
 *
 * Why a build step rather than reading 5etools' own files at runtime:
 *
 *   - `_copy`. A quarter of the bestiary (1141 of 4528 creatures) is defined as
 *     a diff against another statblock, and magic items are generated by
 *     crossing base items with variants. Resolving that needs 5etools' loader,
 *     which is a large browser-oriented dependency we do not want in the app
 *     bundle. Here it runs once, in Node, and the app only ever sees finished
 *     records.
 *   - Shape. 5etools models rules text as a tag language over nested entry
 *     trees; the screen wants flat prose. Converting once beats converting on
 *     every render.
 *   - Size. The raw `data/` directory is ~108 MB. What comes out the other end
 *     is a small search index plus content shards, so a search costs one cached
 *     index and opening a statblock costs one shard.
 *
 * Output (default `public/5etools/`):
 *
 *   manifest.json            source books, per-kind counts, shard size
 *   <kind>/index.json        compact rows, everything search needs
 *   <kind>/<nnn>.json        full records, one shard at a time
 *
 * The generated directory is gitignored on purpose: it is derived from the
 * operator's own copy of the data and is not ours to redistribute.
 */

import fs from 'node:fs'
import path from 'node:path'
import { pathToFileURL } from 'node:url'

import {
	convertMonster, convertSpell, convertItem, convertRule, docSlug, dedupeSlugs, applyCopy,
} from '../src/lib/fivetools-convert.mjs'

/* ------------------------------------------------------------------ args */

function parseArgs (argv) {
	const out = { src: process.env.FIVETOOLS_SRC ?? '', out: 'public/5etools', brew: [], shard: 120, ua: true }
	for (let i = 0; i < argv.length; i++) {
		const a = argv[i]
		if (a === '--src') out.src = argv[++i]
		else if (a === '--out') out.out = argv[++i]
		else if (a === '--brew') out.brew.push(argv[++i])
		else if (a === '--shard') out.shard = Math.max(20, parseInt(argv[++i], 10) || 120)
		else if (a === '--no-ua') out.ua = false
		else if (a === '--help' || a === '-h') out.help = true
	}
	return out
}

const args = parseArgs(process.argv.slice(2))

if (args.help || !args.src) {
	console.log(`
5etools → DM Screen katalog dışa aktarımı

  node scripts/export-5etools.mjs --src <5etools-kaynak-dizini> [seçenekler]

  --src <dir>     5etools kaynak kopyasının kökü (data/ ve js/ içeren dizin)
  --out <dir>     Çıktı dizini (varsayılan: public/5etools)
  --brew <dir>    Ek 5etools homebrew JSON dizini (birden çok kez verilebilir)
  --shard <n>     Parça başına kayıt sayısı (varsayılan: 120)
  --no-ua         Unearthed Arcana / prerelease kaynaklarını dışarıda bırak

  FIVETOOLS_SRC ortam değişkeni --src yerine kullanılabilir.
`)
	process.exit(args.help ? 0 : 1)
}

// Resolved against the invocation cwd, before the chdir below moves it.
const SRC = path.resolve(args.src)
const OUT = path.resolve(args.out)
const BREW_DIRS = args.brew.map((d) => path.resolve(d))

for (const probe of ['data', 'js']) {
	if (!fs.existsSync(path.join(SRC, probe))) {
		console.error(`✕ ${SRC} bir 5etools kaynak dizinine benzemiyor (${probe}/ yok).`)
		process.exit(1)
	}
}

/* ------------------------------------------------------------------ boot */

/**
 * 5etools' loaders resolve data paths relative to the process cwd and hang
 * their API off globals, so the only way to drive them is to become the
 * 5etools working directory for the duration.
 */
process.chdir(SRC)

const mod = (rel) => import(pathToFileURL(path.join(SRC, rel)).href)

await mod('js/parser.js')
await mod('js/utils.js')
await mod('js/utils-dataloader.js')
await mod('js/utils-config.js')
await mod('js/render.js')
await mod('js/render-dice.js')
const ut = await mod('node/util.js')

// Swaps 5etools' XHR-based JSON loader for a filesystem one.
ut.patchLoadJson()

const { Parser, Renderer, DataUtil, SourceUtil } = globalThis

/* --------------------------------------------------------------- sources */

/** slug → { slug, title, abbr }, assigned an index so rows can point at it. */
const sourceBook = new Map()
const sourceOrder = []

function sourceRef (abbr, titleOverride) {
	const slug = docSlug(abbr)
	if (!sourceBook.has(slug)) {
		const title = titleOverride ?? (Parser.sourceJsonToFull ? Parser.sourceJsonToFull(abbr) : String(abbr))
		sourceBook.set(slug, sourceOrder.length)
		sourceOrder.push({ slug, title: String(title), abbr: String(abbr ?? '') })
	}
	return sourceBook.get(slug)
}

function isExcluded (abbr) {
	if (args.ua) return false
	try {
		return !!SourceUtil?.isNonstandardSource?.(abbr)
	} catch {
		return false
	}
}

/* ---------------------------------------------------------- spell classes */

/**
 * Spell → class lists moved out of the spell files and into a generated
 * lookup, so the class column has to be stitched back on here.
 */
const spellClasses = (() => {
	const file = path.join(SRC, 'data/generated/gendata-spell-source-lookup.json')
	if (!fs.existsSync(file)) return () => []
	const lookup = JSON.parse(fs.readFileSync(file, 'utf8'))
	return (sp) => {
		const bySource = lookup[String(sp.source ?? '').toLowerCase()]
		const entry = bySource?.[String(sp.name ?? '').toLowerCase()]
		if (!entry?.class) return []
		const names = new Set()
		for (const byBook of Object.values(entry.class)) {
			for (const cls of Object.keys(byBook)) names.add(cls)
		}
		return [...names].sort()
	}
})()

/* ------------------------------------------------------------------ brew */

function listBrewFiles () {
	const dirs = [path.join(SRC, 'homebrew'), ...BREW_DIRS]
	const files = []
	for (const dir of dirs) {
		if (!fs.existsSync(dir)) continue
		for (const name of fs.readdirSync(dir)) {
			// `index.json` is 5etools' loader manifest, not brew content.
			if (!name.endsWith('.json') || name === 'index.json') continue
			files.push(path.join(dir, name))
		}
	}
	return files
}

/* ------------------------------------------------------------- collectors */

const monsters = []
const spells = []
const items = []
const rules = []

function pushConverted (bucket, list, convert) {
	for (const raw of list) {
		if (!raw?.name || isExcluded(raw.source)) continue
		try {
			bucket.push(convert(raw))
		} catch (err) {
			console.warn(`  ! "${raw.name}" (${raw.source}) atlandı: ${err.message}`)
		}
	}
}

console.log(`5etools kaynağı: ${SRC}`)

const t0 = Date.now()

/* ---- official ---- */

const rawMonsters = await DataUtil.monster.pLoadAll()
pushConverted(monsters, rawMonsters, (m) =>
	convertMonster(m, { sourceTitle: sourceOrder[sourceRef(m.source)].title }))
console.log(`  yaratıklar: ${monsters.length}`)

const rawSpells = await DataUtil.spell.pLoadAll()
pushConverted(spells, rawSpells, (s) =>
	convertSpell(s, { sourceTitle: sourceOrder[sourceRef(s.source)].title, classes: spellClasses(s) }))
console.log(`  büyüler:    ${spells.length}`)

// Includes generated magic variants ("+1 Longsword"), which is most of the
// value — those exist nowhere as standalone records.
const rawItems = await Renderer.item.pBuildList()
pushConverted(items, rawItems, (i) =>
	convertItem(i, { sourceTitle: sourceOrder[sourceRef(i.source)].title }))
console.log(`  eşyalar:    ${items.length}`)

const RULE_FILES = [
	['data/conditionsdiseases.json', [['condition', 'condition'], ['disease', 'disease'], ['status', 'status']]],
	['data/actions.json', [['action', 'action']]],
	['data/variantrules.json', [['variantrule', 'variantrule']]],
	['data/senses.json', [['sense', 'sense']]],
	['data/skills.json', [['skill', 'skill']]],
]

for (const [rel, kinds] of RULE_FILES) {
	const file = path.join(SRC, rel)
	if (!fs.existsSync(file)) continue
	const json = JSON.parse(fs.readFileSync(file, 'utf8'))
	for (const [key, kind] of kinds) {
		pushConverted(rules, json[key] ?? [], (r) =>
			convertRule(r, { kind, sourceTitle: sourceOrder[sourceRef(r.source)].title }))
	}
}
console.log(`  kurallar:   ${rules.length}`)

/* ---- homebrew ---- */

const brewFiles = listBrewFiles()
let brewCount = 0

for (const file of brewFiles) {
	let json
	try {
		json = JSON.parse(fs.readFileSync(file, 'utf8'))
	} catch (err) {
		console.warn(`  ! ${path.basename(file)} okunamadı: ${err.message}`)
		continue
	}

	// Brew books are not in Parser's source table, so their titles come from
	// the file's own `_meta.sources`.
	for (const s of json?._meta?.sources ?? []) {
		if (s?.json) sourceRef(s.json, s.full ?? s.abbreviation ?? s.json)
	}
	const titleFor = (abbr) => sourceOrder[sourceRef(abbr)].title
	const opts = (abbr) => ({ sourceTitle: titleFor(abbr), homebrew: true })

	const before = monsters.length + spells.length + items.length + rules.length

	/**
	 * Brew leans on `_copy` even harder than the official books do — "the MM
	 * dragon, but bigger" is the normal way to write one. Resolve against the
	 * brew's own entries first, then the official catalogue, so a brew can
	 * inherit from either.
	 */
	const resolved = (list, official) => {
		const arr = Array.isArray(list) ? list : []
		const pool = [...arr, ...official]
		return arr.map((e) => (e?._copy ? applyCopy(e, pool) : e))
	}

	pushConverted(monsters, resolved(json.monster, rawMonsters), (m) => convertMonster(m, opts(m.source)))
	pushConverted(spells, resolved(json.spell, rawSpells), (s) => convertSpell(s, opts(s.source)))
	pushConverted(items, resolved([...(json.item ?? []), ...(json.baseitem ?? [])], rawItems), (i) =>
		convertItem(i, opts(i.source)))
	for (const [key, kind] of [['condition', 'condition'], ['disease', 'disease'], ['action', 'action'], ['variantrule', 'variantrule']]) {
		pushConverted(rules, json[key] ?? [], (r) => convertRule(r, { ...opts(r.source), kind }))
	}

	const added = monsters.length + spells.length + items.length + rules.length - before
	brewCount += added
	console.log(`  homebrew:   ${path.basename(file)} → ${added}`)
}

ut.unpatchLoadJson()

/* ------------------------------------------------------------------ write */

/** Compact index rows — one array per kind, decoded back in the browser. */
const ROW = {
	monsters: (m, shard) => [m.slug, m.name, m.size, m.type, m.cr, sourceBook.get(m.document__slug) ?? 0, m.homebrew ? 1 : 0, shard],
	spells: (s, shard) => [s.slug, s.name, s.level_int, s.school, sourceBook.get(s.document__slug) ?? 0, s.homebrew ? 1 : 0, shard],
	items: (i, shard) => [i.slug, i.name, i.rarity, i.type, sourceBook.get(i.document__slug) ?? 0, i.homebrew ? 1 : 0, shard],
	rules: (r, shard) => [r.slug, r.name, r.kind, sourceBook.get(r.document__slug) ?? 0, r.homebrew ? 1 : 0, shard],
}

function writeKind (kind, records) {
	const dir = path.join(OUT, kind)
	fs.rmSync(dir, { recursive: true, force: true })
	fs.mkdirSync(dir, { recursive: true })

	// Sorting before sharding keeps a book's creatures near each other, so the
	// shard a DM pulls for one goblin usually already holds the next one. It
	// also fixes the order collision numbering depends on.
	records.sort((a, b) => a.name.localeCompare(b.name, 'en') || a.slug.localeCompare(b.slug))
	dedupeSlugs(records)

	const index = []
	let bytes = 0
	for (let start = 0, shard = 0; start < records.length; start += args.shard, shard++) {
		const slice = records.slice(start, start + args.shard)
		const body = JSON.stringify(slice)
		bytes += body.length
		fs.writeFileSync(path.join(dir, `${String(shard).padStart(3, '0')}.json`), body)
		for (const rec of slice) index.push(ROW[kind](rec, shard))
	}

	const indexBody = JSON.stringify(index)
	fs.writeFileSync(path.join(dir, 'index.json'), indexBody)

	return {
		count: records.length,
		shards: Math.ceil(records.length / args.shard),
		indexBytes: indexBody.length,
		shardBytes: bytes,
	}
}

fs.mkdirSync(OUT, { recursive: true })

const kinds = {
	monsters: writeKind('monsters', monsters),
	spells: writeKind('spells', spells),
	items: writeKind('items', items),
	rules: writeKind('rules', rules),
}

/** Only advertise books that actually contributed something. */
const used = new Set([
	...monsters.map((m) => m.document__slug),
	...spells.map((s) => s.document__slug),
	...items.map((i) => i.document__slug),
	...rules.map((r) => r.document__slug),
])

const manifest = {
	format: 'dm-screen-5etools/1',
	generatedAt: Date.now(),
	shardSize: args.shard,
	sources: sourceOrder.map((s, i) => ({ ...s, index: i, used: used.has(s.slug) })),
	kinds,
}

fs.writeFileSync(path.join(OUT, 'manifest.json'), JSON.stringify(manifest))

const mb = (n) => `${(n / 1024 / 1024).toFixed(1)} MB`
const total = Object.values(kinds).reduce((acc, k) => acc + k.indexBytes + k.shardBytes, 0)

console.log(`\n✓ ${OUT}`)
for (const [kind, k] of Object.entries(kinds)) {
	console.log(`  ${kind.padEnd(9)} ${String(k.count).padStart(5)} kayıt · ${k.shards} parça · dizin ${(k.indexBytes / 1024).toFixed(0)} KB`)
}
console.log(`  toplam    ${mb(total)} · ${sourceOrder.length} kaynak · ${brewCount} homebrew kayıt · ${Date.now() - t0}ms`)
